### PR TITLE
Update "Admin", "feed's related item" & "Goto Dashboard" button icons

### PR DESCRIPTION
**Pull request by theskumar**
- Rename "Apply Admin" to "Admin" 
- Adds "Admin" icon to the user's profile page along with the "Dashboard" link, makes it easier to goto admin without going to dashboard everytime first.
- Update icons for "dashboard" and "Admin" to use heroicons.
- Update activity feed related link icon + it's visuals
- Remove `arrow-head-pixels--solid` icon from the sprite as it's no longer in use anywhere.

Screenshot 2024-05-09 at 6  40 41@2x

---

Screenshot 2024-05-09 at 6  40 57@2x

---

Screenshot 2024-05-09 at 6  41 06@2x

---

Screenshot 2024-05-09 at 7  10 26@2x

## Test Steps

 - [ ] View dashboards of different users, staff, contracting etc. 
 - [ ] check profile page with access to admin 
 - [ ] Check related item link in the activity feed.

### CODE REVIEW

**Review by frjo — APPROVED** [review]
Looks good. Renaming it to plain "Admin" makes it clearer, there are only one admin area. We also plan to add "Admin" to the new coming user dropdown menu.

**Review by wes-otf — APPROVED** [review]
this is great! a lot more intuitive I think.

**Comment by wes-otf** [comment]
Tested, all looked good just a weird thing when I was either Contracting or Finance is that the `Admin` option would show up on my dashboard, but not on my profile settings. Also couldn't access it and would return a ton of errors when selecting it (Finance admin button also didn't have the icon, but prob doesn't matter):
Screenshot 2024-05-21 at 16 47 57
Screenshot 2024-05-21 at 16 48 06
Screenshot 2024-05-21 at 16 48 46

**Comment by frjo** [comment]
@wes-otf @theskumar That was an old bug where we missed to check `perms.wagtailadmin.access_admin` on these dashboards. I have fixed that in the PR now.

**Comment by wes-otf** [comment]
Looks good on test!

**Pull request merged**
