### PR TITLE
Enable overwritting of django template forms and update apps to not clash

### PR DESCRIPTION
**Pull request by todd-dembrey**
We need to change one of the base form templates. django.forms will then conflict so i have updated the app labels to fix this.

https://docs.djangoproject.com/en/1.11/ref/forms/renderers/#overriding-built-in-widget-templates

@chris-lawton For reference

### CODE REVIEW

**Comment by zerolab** [comment]
LGTM

@chris-lawton this allows you to customise the form element widgets in `opentech/public/forms/templates/django/forms/widgets/` or globally in `opentech/templates/django/forms/widgets/`

**Comment by zerolab** [comment]
@todd-dembrey see tests fail

**Comment by todd-dembrey** [comment]
I was going to recommend `opentech/templates/django/forms/widgets/` for this point in time.

**Comment by zerolab** [comment]
`form_lanading_page.html`

**Comment by todd-dembrey** [comment]
This should create a new table under the new app_name for the staging server. Seeing as we currently have no content in this table i'm happy for that to happen here. It may be worth clearing content types if we get issue.

**Pull request merged**
